
[workspace]
resolver = "2"
members = [
    "bins/*",
    "crates/*",
]
default-members = ["crates/cvm"]

[profile.release]
lto = true
codegen-units = 1

[profile.ethtests]
inherits = "test"
opt-level = 3